#pragma once

#include "Utilidades.h"
#include "Cinematica.h"

Cinematica setupCinNvl1Inicio() {
	Cinematica cin;

	cin.agregarSlide({
		u8"▄▄  ▄▄ ▄▄ ▄▄ ▄▄      ▄██     ▄▄▄▄▄ ▄▄       ▄▄▄▄ ▄▄ ▄▄    ▄▄▄▄▄ ▄▄  ▄▄  ▄▄▄▄ ▄▄  ▄▄▄    ▄▄▄▄  ▄▄▄▄▄ ▄▄      ▄▄▄▄  ▄▄  ▄▄▄ ",
		u8"███▄██ ██▄██ ██       ██ ▀   ██▄▄  ██      ███▄▄ ██ ██    ██▄▄  ███▄██ ██▀▀▀ ██ ██▀██   ██▀██ ██▄▄  ██      ██▄█▄ ██ ██▀██",
		u8"██ ▀██  ▀█▀  ██▄▄▄    ██ ▄   ██▄▄▄ ██▄▄▄   ▄▄██▀ ██ ██▄▄▄ ██▄▄▄ ██ ▀██ ▀████ ██ ▀███▀   ████▀ ██▄▄▄ ██▄▄▄   ██ ██ ██ ▀███▀",
		u8" ",
		u8" ",
		u8"                  ┏━┓╻┏━┓   ┏━╸┏┓╻┏━╸     ┏━┓┏━╸╻  ╻ ╻┏━┓   ┏━╸┏━╸┏┓╻╺┳╸┏━┓┏━┓╻       ┏━┓┏━╸┏━┓╻ ╻                  ",
		u8"                  ┣┳┛┃┃ ┃   ┣╸ ┃┗┫┣╸      ┗━┓┣╸ ┃  ┃┏┛┣━┫   ┃  ┣╸ ┃┗┫ ┃ ┣┳┛┣━┫┃       ┣━┛┣╸ ┣┳┛┃ ┃                  ",
		u8"                  ╹┗╸╹┗━┛   ┗━╸╹ ╹┗━╸ ┛   ┗━┛┗━╸┗━╸┗┛ ╹ ╹   ┗━╸┗━╸╹ ╹ ╹ ╹┗╸╹ ╹┗━╸ ┛   ╹  ┗━╸╹┗╸┗━┛                  ",
		u8"                                                                                                                    ",
		u8"                                                                                                                    ",
		u8" ┃ ┏━┓╻ ╻┏━╸╺┳┓┏━╸   ╻ ╻┏┓╻   ┏━╸┏━┓┏━┓┏━┓┏━┓╺┳╸┏━╸┏━┓┏━┓   ┏━╸┏━┓┏━╸╻ ╻┏━╸╻ ╻┏━┓┏━┓   ╻ ╻┏┓╻┏━┓   ╻ ╻╻┏━┓╺┳╸┏━┓┏━┓╻┏━┓",
		u8"┏━ ┣━┛┃ ┃┣╸  ┃┃┣╸    ┃ ┃┃┗┫   ┣╸ ┃ ┃┣┳┛┣━┫┗━┓ ┃ ┣╸ ┣┳┛┃ ┃   ┣╸ ┗━┓┃  ┃ ┃┃  ┣━┫┣━┫┣┳┛   ┃ ┃┃┗┫┣━┫   ┣━┫┃┗━┓ ┃ ┃ ┃┣┳┛┃┣━┫",
		u8"┗━┛╹  ┗━┛┗━╸╺┻┛┗━╸   ┗━┛╹ ╹   ╹  ┗━┛╹┗╸╹ ╹┗━┛ ╹ ┗━╸╹┗╸┗━┛   ┗━╸┗━┛┗━╸┗━┛┗━╸╹ ╹╹ ╹╹┗╸   ┗━┛╹ ╹╹ ╹   ╹ ╹╹┗━┛ ╹ ┗━┛╹┗╸╹╹ ╹",
		u8"         ┏━┓╻ ╻┏━╸   ┏┓╻┏━┓   ┏━┓┏━╸   ┏━╸╻ ╻┏━╸┏┓╻╺┳╸┏━┓   ┏━╸┏━┓┏┓╻   ┏━┓┏━┓╻  ┏━┓┏┓ ┏━┓┏━┓┏━┓┏━┓                 ",
		u8"         ┃┓┃┃ ┃┣╸    ┃┗┫┃ ┃   ┗━┓┣╸    ┃  ┃ ┃┣╸ ┃┗┫ ┃ ┣━┫   ┃  ┃ ┃┃┗┫   ┣━┛┣━┫┃  ┣━┫┣┻┓┣┳┛┣━┫┗━┓ ╺┛                 ",
		u8"         ┗┻┛┗━┛┗━╸   ╹ ╹┗━┛   ┗━┛┗━╸   ┗━╸┗━┛┗━╸╹ ╹ ╹ ╹ ╹   ┗━╸┗━┛╹ ╹   ╹  ╹ ╹┗━╸╹ ╹┗━┛╹┗╸╹ ╹┗━┛ ╹                  ",
		u8"                                                                                                                    ",
		u8"                                                                                                                    ",
		u8"    ┏━ ╺┳╸┏━╸┏━╸╻  ┏━┓┏━┓   ╺┳┓╻┏━┓ ━┓   ┏━╸┏━┓┏┓╻╺┳╸╻┏┓╻╻ ╻┏━┓┏━┓         ┏━ ┏━╸┏━┓┏━╸ ━┓   ┏━┓┏━┓╻  ╺┳╸┏━┓┏━┓                   ",
		u8"    ┃   ┃ ┣╸ ┃  ┃  ┣━┫┗━┓    ┃┃┃┣┳┛  ┃   ┃  ┃ ┃┃┗┫ ┃ ┃┃┗┫┃ ┃┣━┫┣┳┛   ╺━╸   ┃  ┣╸ ┗━┓┃    ┃   ┗━┓┣━┫┃   ┃ ┣━┫┣┳┛                   ",
		u8"    ┗━  ╹ ┗━╸┗━╸┗━╸╹ ╹┗━┛   ╺┻┛╹╹┗╸ ━┛   ┗━╸┗━┛╹ ╹ ╹ ╹╹ ╹┗━┛╹ ╹╹┗╸         ┗━ ┗━╸┗━┛┗━╸ ━┛   ┗━┛╹ ╹┗━╸ ╹ ╹ ╹╹┗╸                   ",
		}, 8, 7);

	cin.agregarSlide({
		u8"“Remontar ese río era como viajar de  regreso a los primeros orígenes del mundo,",
		u8" cuando la vegetación se  desbordaba  sobre la tierra y los grandes árboles eran",
		u8" reyes. Un curso de agua vacío,  un  gran silencio, una selva impenetrable.   El",
		u8" aire era cálido, espeso, pesado,  lento. No había alegría en el fulgor del sol.",
		u8" [...] Y esa quietud de la vida no se parecía en absoluto a  la  paz.     Era la",
		u8" quietud  de  una  fuerza   implacable   que   se  cernía  sobre  una  intención",
		u8" inescrutable. Te miraba con un aire vengativo.”",
		u8"                                              — Joseph Conrad, Heart of Darkness",
		u8"",
		u8" Cuando viajé por primera a  través  del  Río  Ene, entendí por qué los nativos,",
		u8" entendí por qué  los  nativos  dicen  que  los  ríos  tienen alma. Turbulencia.",
		u8" Estruendo. Desasosiego. Extenuación. Era como si la Providencia, a través de la",
		u8" voz de la  naturaleza, estuviese  recitando  la  elegía  de la defunción de sus",
		u8" guardianes. Estuve así por tres largos días, acompañado, gracias a Dios, por un",
		u8" remero, el único que aceptó llevarme a Kametsa Pampa. Tres días de un calor so-",
		u8" focante, de mosquitos zumbando  en  el oído, y de sentir en carne propia la Ira",
		u8" de Dios... un  concepto  no  ajeno   ni   a   los nativos ni a los exploradores",
		u8" españoles que penetraron estas faces hace cinco centurias.",
		u8"",
		u8" Yo no soy tan diferente a  ellos. Yo  también  estoy  movido  por la codicia...",
		u8" de conocimiento. Ansias por descubrir, no  solo la verde beldad de Natura, sino",
		u8" de aquello que no se cuenta con palabras.",
		u8" De lo que todos parlan con laudable actitud,  de  aquello que todos buscan pero",
		u8" que pocos defienden: la Verdad (sí, con mayúscula)..."
		}, 29, 5);

	cin.agregarSlide({
		u8" Llamádme Mateo.  Soy periodista  de  profesión. 12 años en la carrera, 7 de los",
		u8" cuales pasé en Crónica Viva.",
		u8"",
		u8" Ah, Crónica Viva.  Famosa en su inexistente fama e infame por su crudo impacto.",
		u8" Una revista cualquiera que no resalta en nada: ni en la verborrea de sus escri-",
		u8" tores ni en el carisma de sus  presentadores... salvo  por el único aspecto que",
		u8" de verdad importa: su inquebrantable monomanía por la VERDAD.",
		u8"",
		u8" He viajado por toda la patria.  He seguido los rastros de organizaciones crimi-",
		u8" nales en Lima, he cubierto derrames mineros  en  Pasco,  desapariciones  en  el",
		u8" VRAEM... siempre  armado  con  nada  más  que  una  grabadora, una cámara y  mi",
		u8" verboso ser. Pero nunca, nunca... me he adentrado tanto en la selva...",
		u8"",
		u8" Lo que me trajo aquí: fotografías satelitales.  Obscuridad sobre el manto verde",
		u8" de la Amazonía. Y un dato: en los últimos dos años, ningún periodista ha llega-",
		u8" do a Kametsa Pampa. Los que lo intentaron cambiaron misteriosamente su rumbo en",
		u8" el camino, o regresaban con una lacónica explicación de su laxitud.",
		u8" ",
		u8" Antes de partir, mi editor me dijo: 'Consigue la historia.  Pero no te metas en",
		u8" problemas. Parece que se le olvidó que nosotros somos EL problema..."
		}, 29, 7);

	cin.agregarSlide({
		u8" En la noche del tercer día, paramos en el sendero que conducía hacia Puerto Es-",
		u8" peranza— nombre en  castellano  cuya  peculiaridad no podía ignorar. El remero,",
		u8" sin embargo, se negó a  llevarme,  mas  accedió a acompañarme a pasar la última",
		u8" noche conmigo. Al amanecer, y antes de partir, me suplicó que sea cauto.",
		u8" Y así, sin darme más explicaciones, se marchó río abajo.",
		u8" ",
		u8" El sendero había sido obscurecido por la gruesa neblina. No había más ruido que",
		u8" mi propia respiración, el  sonido  del agua fluyendo y algunos monos aulladores",
		u8" que chillaban en la distancia. La selva me miraba con un aire vengativo.",
		u8"",
		u8" Y me di cuenta que no estaba solo.  Dos hombres, jóvenes, robustos, se pusieron",
		u8" en cada uno de mis costados. Intenté mantener la calma... pero,  ¿cómo no hacer",
		u8" la tan obvia conexión entre datos supuestamente tan dispares?   Los periodistas",
		u8" que cambiaban su rumbo, los murmullos del remero, y esta extraña presencia...",
		u8"",
		u8" HOMBRE 1: ¿Periodista, eh? Te estábamos esperando."
		u8" ",
		u8" Una mísera noche y ya había sido marcado, ¡Cómo me sonreía el sino!",
		u8" Hice lo que pude para contener una risilla histérica.  Era  todo tan abusurdo,",
		u8" pero a la vez tan obvio que me sentí el hombre más estúpido del mundo."
		u8" ",
		u8" HOMBRE 2: El monte es grande, foreastero. Fácil perderse. Y nadie va a ayudarte."
		}, 29, 7);

	cin.agregarSlide({
		u8" El primero se acercó más. Pude oler el fantasma del tabaco en su aliento y las",
		u8" manchas de aceite en su torso. Tenía en su faz una sonrisa burlona, y sus ges-",
		u8" tos estaban manchados hasta el tuétano con una parsimonia agobiante.  Era cómo",
		u8" si fuese un profesor lidiando con un lerdo infante.",
		u8"",
		u8" HOMBRE 1: Mira, te voy a dar un consejo. Tú tomas tus fotos bonitas,  escribes",
		u8" tu nota y te largas río abajo. En dos días llegas a  Satipo.  En  dos  más,  a",
		u8" Lima... Piensa en tu familia. En  tu  carrera.  Y  en  el brillante futuro que",
		u8" tienes por delante. Aquí no hay historia, solo gente que no quiere hablar  con",
		u8" extraños, ¿Entendiste?",
		u8"",
		u8" El segundo hombre no se molestó en hablar, respondiendo con  una  carcajada  a",
		u8" pulmón junto a  una  peculiar  mirada:  dudando  si  verme con la pena que uno",
		u8" siente al ver a un  desquiciado,  o con la molestia que invade cuando ves a un",
		u8" insecto.",
		u8"",
		u8" No les respondí.  Consentir  era  futil.  Hablar  era  darles  bagatelas. Y el",
		u8" silencio... era temerario...",
		u8" ",
		u8" No se marcharon. Simplemente marcharon algunos pasos sendero arriba y se  que-",
		u8" daron allí, observando, y esperando ¿A qué? ¿A qué abriera la boca? ¿O buscan-",
		u8" la razón para que su florida verborrea evolucione al poco elegante arte de los",
		u8" puños?"
		}, 29, 6);

	return cin;
}

Cinematica setupCinNvl1Final() {
	Cinematica cin;

	cin.agregarSlide({
		u8" La brisa sopla, mesiendo los árboles, los arbustos y la maleza. Un manto dorado",
		u8" cubre el pasto donde estoy reposando.  Es el crepúsculo.  En menos de una hora,",
		u8" el sol se esconderá completamente, abriendo paso a la luna, cumpliendo la eter-",
		u8" na pero necesaria dualidad entre la luz y la oscuridad. Miro al horizonte. Sien",
		u8" to que la naturaleza me susurra, me atrapa, me seduce. ¿Y si de verdad las plan",
		u8" tas tienen alma? Me pregunto, mientras fumo un poco del tabaco que el Abuelo To",
		u8" más me dio esa misma mañana.",
		u8"",
		u8" Ahí es cuando siento una presencia detrás de mí. Antes de que pueda reaccionar,",
		u8" siento una mano en mi hombro. Alzo la mirada. Reconozco inmediatamente ese ros-",
		u8" tro. Es Wilmer. Está más cansado que cuando lo vi por primera vez, esa misma ma",
		u8" ñana, pero hay una extrañeza en su faz. Un sutil, traicionero, rayo de esperan-",
		u8" za. Se me queda observando por un largo intervalo, hasta que rompe el silencio.",
		u8"",
		u8" WILMER: Le caíste bien a Doña Rosa. Mamá Clara preguntó por ti.  Don Tomás dice",
		u8" que sabes escuchar. Estoy sorprendido... Eso es raro en un forastero.",
		u8"",
		u8" Hace una pausa, dudando si cruzar el umbral del que jamás regresará.",
		u8"",
		u8" WILMER: El Abuelo Evaristo quiere verte."
		}, 29, 7);

	cin.agregarSlide({
		u8" Caminamos un largo sendero en total silencio. No es la lúgubre carencia de soni",
		u8" do de las interminables noches de viaje. Es algo diferente. Lleno en su flaque-",
		u8" za. Los últimos sonidos distantes,  los murmullos, los gritos,  la indiscutible",
		u8" VIDA de un pueblo que se niega a fenecer, desaparece a nuestras espaldas.  Y la",
		u8" naturaleza, tan atenta, parece notar este hecho.",
		u8" ",
		u8" WILMER: Don Evaristo es el líder del pueblo. Él es el último que lo recuerda to",
		u8" do. Nuestra fundación. Los nombres de nuestros ancestros. Los lugares donde so-",
		u8" líamos pescar y cosechar nuestros cultivos.  Los cantos tradicionales y los ri-",
		u8" tuales que abundaban antes que llegaran los madereros.  Por eso es que le tene-",
		u8" mos tanto respeto. Porque es la personificación del pueblo.   Si él se va, todo",
		u8" el pueblo se va con él.",
		u8"",
		u8" MATEO: ¿Y por qué no se lo enseña todo lo que sabe a la juventud?   Al fin y al",
		u8" cabo, alguna vez él también fue joven.   Y no hay más regalo más grande que dar",
		u8" la responsabilidad de la superviviencia de un pueblo a las futuras generaciones",
		u8"",
		u8" WILMER: Antes había comunión con la naturaleza. El hombre y la tierra eran uno.",
		u8" No se parasitaba. Se daba y se recibía. Y fue así por siglos. Y gracias a ello,",
		u8" es que nuestro pueblo se mantuvo saludable. Pero con los madereros, eso se rom-",
		u8" pió. Los jóvenes nacieron desarraigados.  Rechazan la tierra, por que la tierra",
		u8" ellos creen, los rechazó. Y ellos se van. O trabajan para ellos.  O simplemente",
		u8" mueren muy jóvenes. Y los que quedamos... estamos cansados."
		u8" ",
		u8" Reanuda la marcha. El sendero se estrecha. Las ramas nos arañan los brazos.",
		}, 29, 5);

	cin.agregarSlide({
		u8" El sendero desemboca en un claro. Allí, solitaria, hay una ceiba gigante.   Mi",
		u8" vida en Lima pasa por mi mente al verla. Es tan alta como esos edificios resi-",
		u8" denciales que abundan en San Isidro, o en Jesús María.   Y es tan ancha que se",
		u8" se necesitaría más de cinco hombres para abrazarla.",
		u8"",
		u8" Al costado, una cabaña de madera. Y un techo de palma.  Es pequeña, pero bien ",
		u8" cuidada.   Y mentiría si digo que no sentí un estallido de emociones al verla.",
		u8" Tiene ese aire peculiar de los lugares que sienten, que recuerdan millares  de",
		u8" recuerdos, de cuitas, de alegrías.",
		u8"",
		u8" De la chimenea sale un humo blanco. Y lo puedo distinguir. Huele a tabaco. Qui",
		u8" zás sea el mismo que me dio Don Tomás, y el cuál aún no había acabado.",
		u8"",
		u8" WILMER: Esta parte es tuya, Mateo. Yo no puedo entrar contigo.",
		u8"",
		u8" Su mirada, furtiva, logra fijarse en mi ser.  Hay una advertencia en sus ojos.",
		u8"",
		u8" WILMER: No le mientas. No le prometas nada que no vayas a cumplir. Y sobre to-",
		u8" do, escucha. Es lo que más nos falta a todos, después de todos."
		}, 29, 7);

	cin.agregarSlide({
		u8" Wilmer se aparta. Estoy completamente solo ante el peligroso umbral. ¿Pero que",
		u8" es mi vida sin este tipo de exaltación?  A lo largo de mi vida, he aprendido a",
		u8" vivir peligrosamente. Y es lo que me ha llevado hasta donde estoy. Pero nunca,",
		u8" nunca, me había  sentido  tan...  débil. Sabía cómo controlar mis nervios ante",
		u8" las amenazas, las extorsiones, los ataques bajos. Pero nunca había lidiado con",
		u8" mi propia incertidumbre...",
		u8"",
		u8" Volteo la cabeza. Wilmer ha desaparecido.  Recuerdo los anteriores reportajes.",
		u8" Aquel reporte de la minería ilegal en Pasco, y del cual volví con una historia",
		u8" indiscutible,  y después del cuál me llovieron muchos agradecimientos en forma",
		u8" de casquillos de bala en mi puerta. Ya estaba acostumbrado al riesgo... Y vol-",
		u8" ví a confirmar que este riesgo era diferente.   Pensé: ¿Cuál es la diferencia?",
		u8"",
		u8" La respuesta estaba alrededor, detrás, y frente mío. El costo social. La admi-",
		u8" ración genuina y el asombro causado por la tenacidad de un pueblo, de la sabi-",
		u8" duría de sus líderes... y un pesar ahogante por el sufrimiento de 'Kipatsi'...",
		u8"",
		u8" No lo pienso más. Empujo la puerta, la cuál había sido dejada convenientemente",
		u8" entreabierta. Las bisagras gimen ante mi invasión.",
		u8"",
		u8" EVARISTO: Pasa, periodista. Te estábamos esperando.",
		u8"",
		u8" No lo logro ver. Pero sé que está ahí. Que... 'ellos' están allí.",
		}, 29, 5);

	return cin;
}

Cinematica setupCinNvl2Inicio() {
	Cinematica cin;

	cin.agregarSlide({
		u8"                ███  ██ ▄▄ ▄▄ ▄▄      ████▄     ██      ▄▄▄     ▄▄▄  ▄▄▄▄  ▄▄ ▄▄    ▄▄     ▄▄▄",
		u8"                ██ ▀▄██ ██▄██ ██       ▄██▀ ▀   ██     ██▀██   ██▀██ ██▄█▄ ██ ██    ██    ██▀██",
		u8"                ██   ██  ▀█▀  ██▄▄▄   ███▄▄ ▄   ██████ ██▀██   ▀███▀ ██ ██ ██ ██▄▄▄ ██▄▄▄ ██▀██",
		u8"                																		",
		u8"                         ▄▄▄  ▄▄▄▄   ▄▄▄  ▄▄  ▄▄ ▄▄▄▄   ▄▄▄  ▄▄  ▄▄  ▄▄▄  ▄▄▄▄   ▄▄▄	",
		u8"                        ██▀██ ██▄██ ██▀██ ███▄██ ██▀██ ██▀██ ███▄██ ██▀██ ██▀██ ██▀██",
		u8"                        ██▀██ ██▄█▀ ██▀██ ██ ▀██ ████▀ ▀███▀ ██ ▀██ ██▀██ ████▀ ██▀██",
		u8" ",
		u8"",
		u8"                                ┏━┓╻ ╻┏━╸┏┓ ┏━┓┏━┓╺┳┓┏━┓   ╻ ╻┏━┓┏┓╻╻┏ ╻┏━┓╻                               ",
		u8"                                ┃┓┃┃ ┃┣╸ ┣┻┓┣┳┛┣━┫ ┃┃┣━┫   ┗┳┛┃ ┃┃┗┫┣┻┓┃┣┳┛┃                               ",
		u8"                                ┗┻┛┗━┛┗━╸┗━┛╹┗╸╹ ╹╺┻┛╹ ╹    ╹ ┗━┛╹ ╹╹ ╹╹╹┗╸╹                               ",
		u8"                                                                                                           ",
		u8"                                                                                                           ",
		u8"               ┃ ╻  ┏━┓   ╺┳╸╻┏━╸┏━┓┏━┓┏━┓   ┏━┓╻ ╻┏━╸   ┏┓╻┏━┓╺┳┓╻┏━╸   ┏━┓┏━╸┏━╸╻  ┏━┓┏┳┓┏━┓             ",
		u8"              ┏━ ┃  ┣━┫    ┃ ┃┣╸ ┣┳┛┣┳┛┣━┫   ┃┓┃┃ ┃┣╸    ┃┗┫┣━┫ ┃┃┃┣╸    ┣┳┛┣╸ ┃  ┃  ┣━┫┃┃┃┣━┫             ",
		u8"              ┗━┛┗━╸╹ ╹    ╹ ╹┗━╸╹┗╸╹┗╸╹ ╹   ┗┻┛┗━┛┗━╸   ╹ ╹╹ ╹╺┻┛╹┗━╸   ╹┗╸┗━╸┗━╸┗━╸╹ ╹╹ ╹╹ ╹             ",
		u8"                        ╺┳┓┏━╸ ┏┓┏━┓   ╺┳┓┏━╸   ┏━┓┏━╸┏━┓   ┏━┓┏━┓┏━╸┏━┓┏━┓╺┳┓┏━┓┏━┓                       ",
		u8"                         ┃┃┣╸   ┃┣━┫    ┃┃┣╸    ┗━┓┣╸ ┣┳┛   ┗━┓┣━┫┃╺┓┣┳┛┣━┫ ┃┃┣━┫ ╺┛                       ",
		u8"                        ╺┻┛┗━╸┗━┛╹ ╹   ╺┻┛┗━╸   ┗━┛┗━╸╹┗╸   ┗━┛╹ ╹┗━┛╹┗╸╹ ╹╺┻┛╹ ╹ ╹                        ",
		u8"                                                                                               ",
		u8"                                                                                ",
		u8"┏━ ╺┳╸┏━╸┏━╸╻  ┏━┓┏━┓   ╺┳┓╻┏━┓ ━┓   ┏━╸┏━┓┏┓╻╺┳╸╻┏┓╻╻ ╻┏━┓┏━┓         ┏━ ┏━╸┏━┓┏━╸ ━┓   ┏━┓┏━┓╻  ╺┳╸┏━┓┏━┓",
		u8"┃   ┃ ┣╸ ┃  ┃  ┣━┫┗━┓    ┃┃┃┣┳┛  ┃   ┃  ┃ ┃┃┗┫ ┃ ┃┃┗┫┃ ┃┣━┫┣┳┛   ╺━╸   ┃  ┣╸ ┗━┓┃    ┃   ┗━┓┣━┫┃   ┃ ┣━┫┣┳┛",
		u8"┗━  ╹ ┗━╸┗━╸┗━╸╹ ╹┗━┛   ╺┻┛╹╹┗╸ ━┛   ┗━╸┗━┛╹ ╹ ╹ ╹╹ ╹┗━┛╹ ╹╹┗╸         ┗━ ┗━╸┗━┛┗━╸ ━┛   ┗━┛╹ ╹┗━╸ ╹ ╹ ╹╹┗╸",
		}, 15, 4);

	cin.agregarSlide({
		u8"“A  los errores  acumulados  por  sus  antepasados  añadieron  aquello  que  sus",
		u8" antepasados  no  conocían:  la  vacilación  y  el  miedo;  Y  así  sucedió  que",
		u8" desaparecieron de la faz de la tierra, y tras ellos quedó un gran silencio.”",
		u8"                                       — Zygmunt Krasiński, La No Divina Comedia",
		u8"",
		u8" El interior de la casa es austero como una celda monacal.    Un catre de madera",
		u8" contra la pared. Una mesa coja con un candila de aceite. Un machete colgado so-",
		u8" bre el marco de la única ventana. Y en el centro, sentado en una silla de cuero",
		u8" gastado... Don Evaristo.",
		u8" ",
		u8" Temerariamente, avanzo un paso para verlo mejor.   La noche ha caído ya, y todo",
		u8" estaría oscuro si no fuese por la luz que la candila emana.   Las sombras no se",
		u8" disipan, pero puedo verlo mejor. Es más anciano de lo que esperaba. Su faz está",
		u8" surcada por las arrugas,   que se impregnan a su piel como los cauces de un río",
		u8" seco. Sus ojos, sin embaro, brillan con la misma intensidad que Sirio, inundan-",
		u8" do la pequeña cabaña con su inquietante presencia."
		u8"",
		u8" Fuma un cigarro de tabaco negro.  El humo, espeso, increíblemente espeso, nubla",
		u8" mi ya precaria visión. Aquel espectáculo, tan surreal, tan etéreo, me hace sen-",
		u8" tir que estoy entrando en trance, en algún escalofriante estado onírico.",
		u8" ",
		u8" No me habla de inmediato. Detrás del manto de humo, me observa. Me escruta. Sus",
		u8" ojos recorren mi rostro con la incredulidad y latente pasión de alguien que es-",
		u8" tudia un tomo que se creía perdido para siempre."
		}, 29, 5);

	cin.agregarSlide({
		u8" EVARISTO: El río me contó que venías.   El río siempre sabe quién llega y quién",
		u8" se va... Wilmer dice que trabajaste con Doña Rosa. Que cargaste yuca si quejar-",
		u8" te. Que te sentaste con el Abuelo Tomás y escuchaste su silencio. Eso... es ra-",
		u8" ro para un hombre de ciudad. Ellos siempre tienen prisa. Siempre quieren respu-",
		u8" estas antes de hacer las preguntas."
		u8"",
		u8" EVARISTO: Pero no es suficiente. Los otros también trabajaron.  También 'ayuda-",
		u8" ron'. Y luego escribieron mentiras, o no escribieron nada. Dime, ¿Por qué debe-",
		u8" ría creer que tú eres diferente?",
		u8"",
		u8" MATEO: No vine a escribir un artículo. Vine a entender. A la gente. A su lucha.",
		u8" Y sobre todo... a la naturaleza. A la Madre Kipatsi.",
		u8"",
		u8" Tenía un montón de respuestas ensayadas, un guion que me sabía de memoria y que",
		u8" repetía siempre que alguien dudaba de mis intenciones.  Pero sabía que ese hom-",
		u8" bre iba a oler mi duplicidad tal cual un tiburón huele sangre a una milla.",
		u8" ",
		u8" Evaristo arquea una ceja.    Es el primer movimiento que veo en toda la intera-",
		u8" cción."
		}, 29, 8);

	cin.agregarSlide({
		u8" EVARISTO: Entender. ¿Sabes cuál es el peso de esa palabra, forastero? El enten-",
		u8" dimiento es el padre de todo el conocimiento.    Y de todas las formas de vida.",
		u8" Pero los taladores también entienden. Entiendieron nuestra situación, y decidie",
		u8" ron aprovecharse de nuestra debilidad.  Entendiero que los guardianes de la Ma-",
		u8" dre Kipatsi habían perdido la valentía que había caracterizado a nuestros ante-",
		u8" pasados y entonces, atacaron.  Y por nuestra inacción, por nuestra cobardía, la",
		u8" naturaleza nos castiga con enfermedades, con destrucción, con sequías y con ham",
		u8" bre.",
		u8" ",
		u8" Se incorpora con dificultad, apoyándose de un bastón de madera negra. Se acerca",
		u8" a la ventana. La luna brilla en el éter, con prodigiosa majestuosidad.",
		u8"",
		u8" EVARISTO: Cuando aún cumplíamos nuestra parte de la comunión, este pueblo vivía",
		u8" del río y de la tierra. La Quebrada Yonkiri era nuestro puerto. Allí lavábamos.",
		u8" Allí pescábamos. Allí bebíamos. Y allí cultivábamos.  El agua era tan clara que",
		u8" podías ver a los peces nadando en el río.",
		u8" Hace dos años, ellos legaron. Lo que tu gente llama 'empresa maderera'. Talaron",
		u8" los árboles de la orilla. Echaron veneno al agua. Los peces murieron en una so-",
		u8" la noche. La tierra se volvió amarga...  Intentamos resistir, pero nuestro pue-",
		u8" blo ya padecía de aquella funesta enfermedad del alma,    aquella patología tan",
		u8" letal, que desarraigaba al hombre de su tierra y lo elevaba por encima de todo.",
		u8" Si el hombre está por encima de todas las creaciones de Dios,  ¿Cuál es el pro-",
		u8" blema con que este lucre con la naturaleza?   ¿Que de malo tiene barrer bosques",
		u8" enteros y envenenar hasta el último cauce?",
		}, 29, 5);

	cin.agregarSlide({
		u8" EVARISTO: Cuando el hombre traiciona ese pacto, de defender la naturaleza, que",
		u8" es su hogar, su moral se pierde.  Cuando el hombre rompe esta milenaria tradi-",
		u8" ción, que lo hacía uno con Kipatsi, ¿Por qué tendría que resistir?",
		u8" Una comunidad sana está basada en el amor a su suelo. Cuando agreden a la tie-",
		u8" rra, agreden a la comunidad. Y esta luchará con todo ante esta agresión.  Pero",
		u8" una gente enferma... no tiene el poder ni la valentía para luchar...",
		u8" ",
		u8" EVARISTO: Ellos tenían papeles. Abogados. Decían que 'habíamos usurpado' el lu",
		u8" gar, que no teníamos los documentos para probar nuestra propiedad.  Yo alzé la",
		u8" voz. Me denunciaron penalmente. Y entonces, retrocedimos. Enfermos del alma, y",
		u8" atados de manos, el único curso era la destrucción y la enfermedad. Y eso pasó",
		u8" ",
		u8" Don Evaristo está visiblemente movido. Pese a su edad, su voz es poderosa. Ca-",
		u8" da palabra tiene el mismo terrorífico impacto de un rayo.  Y la emoción que le",
		u8" pone al hablar es más genuina que la verdad misma.",
		u8"",
		u8" Entonces, él se vuelve hacia mí.   Toma de la pequeña mesa una bolsa hecha con",
		u8" cáscaras de plátanos.",
		u8" ",
		u8" EVARISTO: Kamarampi. La planta sagrada...  Antes de que llegaron los madereros",
		u8" y más cuando nuestro  pueblo  aún  era  sano,  el kamarampi crecía por toda la",
		u8" orilla. Le cantábamos. Le entregábamos ofrendas.    Lo utilizábamos para sanar",
		u8" nuestros espíritus y nuestros cuerpos...",
		}, 29, 5);

	cin.agregarSlide({
		u8" Me extiende las semillas. Sus manos tiemblan ligeramente.",
		u8" ",
		u8" EVARISTO: Quiero que vayas a la Quebrada Yonkiri. Quiero que veas con tus pro-",
		u8" pios ojos lo que hicieron. Y  quiero que plantes estas semillas en cuatro pun-",
		u8" tos de la orilla. Donde antes crecían los árboles más viejos.    Donde nadaban",
		u8" los niños. Donde enterrábamos a nuestros muertos.",
		u8" ",
		u8" MATEO: ¿Eso es todo? ¿Plantar cuatro semillas?",
		u8" ",
		u8" EVARISTO: No. Eso es lo más difícil. Ellos no quieren que nada vuelva a crecer",
		u8" Es el gesto supremo de su victoria sobre nosotros. Vigilan la quebrada.  Día y",
		u8" noche. Si te ven husmeando, te echarán. O algo peor.",
		u8"",
		u8" EVARISTO: Si esos brotes germinan, habremos ganado.   La vida renacerá después",
		u8" de la aparente muerte. Y quizás nuestro pueblo vuelva a ser sano otra vez. Pe-",
		u8" ro... si quieres irte, ahora es el momento.  Puedes llevar el dossier de prue-",
		u8" bas que hemos reunido. Si lo publicas, quizás alguien en Lima escuche.",
		u8" ",
		u8" Es una oferta honrosa. Volver y escribir en la seguridad de mi escritorio, sa-",
		u8" biendo que, aunque lluevan las amenazas, poco o nada me podría pasar. Pero re-",
		u8" cuerdo lo que vi. Recuerdo las cuitas del pueblo.  El pesar de cada uno de sus",
		u8" habitantes. Y sé que si me voy, habría dejado que la muerte gane.",
		}, 29, 6);

	cin.agregarSlide({
	u8" MATEO: Iré a la quebrada. Plantaré las semillas. Y luego volveré.",
	u8" ",
	u8" Don Evaristo asiente lentamente. No parece sorprendido.    Parece que esperaba",
	u8" desde antes esa respuesta. Solamente quería una confirmación.",
	u8" ",
	u8" EVARISTO: Bien. Pero lleva a alguien contigo. Solo, no sobrevivirás.   Lleva a",
	u8" Wilmer contigo. Él conoce el terreno. Y te protegerá.",
	u8" ",
	u8" Se acerca a la mesa, y saca una caja de madera tallada con patrones que no lo-",
	u8" gro reconocer.",
	u8"",
	u8" EVARISTO: Este es nuestro dossier. Dos años de fotos. Testimonios.  Registros.",
	u8" Pruebas. Todo lo que hemos podido reunir durante este tiempo.   Cuando vuelvas",
	u8" de la quebrada, será tuyo. Pero tendrás que ganártelo.",
	u8" ",
	u8" EVARISTO: Una cosa más, periodista. Estas semillas que te entrego son las últi",
	u8" mas de toda Kametsa Pampa.    Si las pierdes, nuestro pueblo se quedará sin su",
	u8" planta sagrada, quizás para siempre.  Y su esperanza de curarse de su enferme-",
	u8" dad de espíritu desaparecerán eternamente en el vacío.    Piensa ello mientras",
	u8" caminas...",
		}, 29, 7);

	return cin;
}

Cinematica setupCinNvl2Final() {
	Cinematica cin;

	cin.agregarSlide({
		u8" ¿Cuánto tiempo hemos estado aquí?   ¿Luchando contra la muerte y las fuerzas de",
		u8" la destrucción? Sé que no es solo lirismo banal. Es una realidad.  Lo siento en",
		u8" mis músculos palpitantes,  en el sudor que se me impregna en todo el cuerpo co-",
		u8" mo una segunda piel, y en el gris horizonte. Aquí hace calor.   El ambiente tó-",
		u8" rrido me recuerda a los mediodías del verano en el Norte.  Es insoportable.  En",
		u8" la aldea, era diferente.   Aquí, el olor de un humo extraño, del cuál logro re-",
		u8" conocer gasolina y azufre, invade cada metro cúbico. Y por encima de todo, sien",
		u8" to aquella brisa funesta propia de los lugares moribundos.",
		u8" ",
		u8" Y, en medio de ese gris páramo, nacieron cuatro brotes.",
		u8" ",
		u8" El propio hecho que algún tipo de vida haya nacido en este claro infernal podrí",
		u8" a anonadar hasta al menos sensible de los hombres.  Pero a eso hay que sumar el",
		u8" hecho que no son plantas cualquiera. Son kamarampi. Son sagradas.  Y su renacer",
		u8" representa el renacer de un pueblo que se niega a fenecer.",
		u8" ",
		u8" Wilmer se acerca. Se arrodilla. Y no dice nada. No necesita hacerlo.  Su respi-",
		u8" ración entrecortada, sus ojos saltados, y sus manos temblorosas hablan más fuer",
		u8" te que cualquier magno soliloquio.",
		u8" ",
		u8" WILMER: Dos años...  —murmura por fin—  Dos años sin ver crecer nada aquí...  Y",
		u8" tú, en una tarde..."
		}, 29, 6);

	cin.agregarSlide({
		u8" Nos quedamos callados.  No solo por cansancio,  o por el asombro  tan magnánimo",
		u8" que invade inclementemente mi razón.  Sino, por respeto.  Respeto a algo que ha",
		u8" cambiado. A un gesto tan simple pero a la vez tan grande. Tan silencioso y a la",
		u8" vez tan estruendoso. Y es que algo ha cambiado.  Hay un tinte de verde entre el",
		u8" manto de cenizas, tierra  infértil  y  maleza que cubría este lugar. Y más aún,",
		u8" por el sacro y tan inquietante silencio que se apoderó del lugar.",
		u8" ",
		u8" No es solo nuestra percepción. Es la realidad. En el gris horizonte, figuras se",
		u8" alejan. Son los taladores. El sonido de las motosierras y hachas contra la made",
		u8" ra se apagan. Y en su lugar, reina un eterno silencio. Entre la bruma, los pue-",
		u8" do distinguir. No se han ido. Están allí. Inmóviles. Quietos. Cautos. Ellos tam",
		u8" bién sienten que algo ha cambiado.",
		u8" ",
		u8" MATEO: ¿Por qué ya no nos atacan ahora? —murmuro.",
		u8" ",
		u8" WILMER: Porque ya no estamos solos. Antes éramos un periodista y un campesino. Y",
		u8" ahora... ahora somos esto. Lo que alguna vez fuimos.  Lo que siempre debimos ser",
		u8" Y ellos notan ese cambio.  Y aunque no lo logren entender, comprenden sus conse-",
		u8" cuencias. Y eso... eso los aterra.",
		u8" ",
		u8" MATEO: Lo que alguna vez fuimos... ¿Te refieres al rol de guardianes de la natu-",
		u8" raleza?",
		u8" ",
		u8" Wilmer se me queda observando. No asiente. Pero un pequeña sonrisa, traicionera,",
		u8" se dibuja en sus labios.",
		}, 29, 5);

	cin.agregarSlide({
		u8" El horizonte gris se extiende sobre toda la selva.  La monocromía ya no es ex-",
		u8" clusiva de aquel páramo infernal que queda detrás de nosotros.  La tierra deja",
		u8" de estar seca y agrietada. La alfombra de cenizas y carbón desaparece. Los to-",
		u8" cones quedan atrás. Y el agua del río cercano empieza a aclararse, libre de la",
		u8" espuma colorida y venenosa que abundaba en las orillas de la  Quebrada Yonkiri",
		u8" y que también hacía presencia en forma de charcos tóxicos.",
		u8" ",
		u8" Natura —o la Madre Kipatsi— nos  recibe  con un pesado silencio.  No es el es-",
		u8" truendo y la inclemencia con la que me recibió días atrás, o la ominosa caren-",
		u8" cia de ruido que servía como  entremés  entre el caos que me había acompañado.",
		u8" Es... diferente. Aún no sé como describirlo. Es menos sofocante. Los árboles y",
		u8" las pequeñas bestias que acechaban entre las ramas,  ya no cuentan con esa mi-",
		u8" rada vengativa que me helaba los huesos. Ahora... son testigas. Las plantas me",
		u8" observan. Siento como que murmuraban acerca de mí. Ya no son amenazantes.",
		u8"",
		u8" El camino se siente mucho menos agobiante.  Quizás sea por el sol que se pone.",
		u8" Porque estamos yendo sendero abajo.  Por que los taladores ya no nos están pi-",
		u8" sando los talones.  O por que sentimos dentro de nosotros aquella extraña sen-",
		u8" sación de una obligación dolorosa y abrumadora,  cuya carga por fin se levanta",
		u8" de nuestros hombros.",
		u8" ",
		u8" Al llegar al lindero del pueblo, reconozco la ceiba gigante. Y también reconoz",
		u8" co a la austera cabaña descansando bajo su umbral.  El humo blanco vulve a sa-",
		u8" lir de la chimenea. Es una invitación."
		}, 29, 5);

	cin.agregarSlide({
		u8" La puerta está entreabierta. Don Evaristo nos está esperando. Y siento que sa-",
		u8" be con anticipación el resultado.  Intercambiamos miradas con Wilmer.   Por un",
		u8" largo momento,  el silencio vuelve a reiner.  Finalmente, él asiente.  Se pone",
		u8" frente mío. Y empuja la puerta.",
		u8" ",
		u8" Ante el manto dorado del crepúsculo, está él. Don Evaristo.  Está recostado en",
		u8" su silla de cuero gastado, con un grueso cigarrillo en una mano y el bastón de",
		u8" madera negra en el otro.    Antes que entraramos, estaba observando la puerta.",
		u8" No pregunta.   Nuestros rostros, las manchas de tierra en nuestra ropa y nues-",
		u8" tro visible agotamiento es la respuesta que él busca.",
		u8"",
		u8" EVARISTO: Las plantaste.",
		u8" ",
		u8" No puedo responder con palabras.  Mi usual verborrea es inútil ante el asombro",
		u8" y profunda... nostalgia, que realentiza mi razón. Solamente asiento.",
		u8" Don Evaristo devuelve el gesto.  Posa su mirada en Wilmer.  Cierra los ojos. Y",
		u8" recita lo que parece ser un agradecimineto, o una oración,  en su nativo ashá-",
		u8" ninka que por su complejidad y mi ignorancia, no logro comprender.",
		u8" ",
		u8" EVARISTO: Pasa, periodista. Ahora sí. Te contaré lo que los de afuera no quie-",
		u8" ren que sepas. Lo que la juventud ha perdido. La historia del origen.",
		}, 29, 6);

	return cin;
}          

Cinematica setupCinNvl3Inicio() {
	Cinematica cin;

	cin.agregarSlide({
		u8"▄▄  ▄▄ ▄▄ ▄▄ ▄▄      ████▄     ▄▄     ▄▄▄    ▄▄   ▄▄ ▄▄▄▄▄ ▄▄   ▄▄  ▄▄▄  ▄▄▄▄  ▄▄  ▄▄▄    ▄▄ ▄▄ ▄▄ ▄▄ ▄▄  ▄▄▄ ",
		u8"███▄██ ██▄██ ██       ▄▄██ ▀   ██    ██▀██   ██▀▄▀██ ██▄▄  ██▀▄▀██ ██▀██ ██▄█▄ ██ ██▀██   ██▄██ ██ ██▄██ ██▀██",
		u8"██ ▀██  ▀█▀  ██▄▄▄   ▄▄▄█▀ ▄   ██▄▄▄ ██▀██   ██   ██ ██▄▄▄ ██   ██ ▀███▀ ██ ██ ██ ██▀██    ▀█▀  ██  ▀█▀  ██▀██",
		u8" ",
		u8" ",
		u8"                    ┏━╸┏━┓┏━┓┏━┓╺━┓┏━┓┏┓╻   ╺┳┓┏━╸   ╻┏ ┏━┓┏┳┓┏━╸╺┳╸┏━┓┏━┓   ┏━┓┏━┓┏┳┓┏━┓┏━┓                  ",
		u8"                    ┃  ┃ ┃┣┳┛┣━┫┏━┛┃ ┃┃┗┫    ┃┃┣╸    ┣┻┓┣━┫┃┃┃┣╸  ┃ ┗━┓┣━┫   ┣━┛┣━┫┃┃┃┣━┛┣━┫                  ",
		u8"                    ┗━╸┗━┛╹┗╸╹ ╹┗━╸┗━┛╹ ╹   ╺┻┛┗━╸   ╹ ╹╹ ╹╹ ╹┗━╸ ╹ ┗━┛╹ ╹   ╹  ╹ ╹╹ ╹╹  ╹ ╹                  ",
		u8"                                                                                                              ",
		u8"    																									         ",
		u8"     ┃ ╺┳┓┏━╸   ┏━┓╻ ╻┏━╸   ┏━┓╻┏━┓╻ ╻┏━╸   ┏━┓┏━┓╻  ╻ ╻┏━┓┏━┓   ╻  ┏━┓   ╺┳╸╻┏━╸┏━┓┏━┓┏━┓   ┏━┓╻   ┏━┓┏━╸    ",
		u8"    ┏━  ┃┃┣╸    ┃┓┃┃ ┃┣╸    ┗━┓┃┣┳┛┃┏┛┣╸    ┗━┓┣━┫┃  ┃┏┛┣━┫┣┳┛   ┃  ┣━┫    ┃ ┃┣╸ ┣┳┛┣┳┛┣━┫   ┗━┓┃   ┗━┓┣╸     ",
		u8"    ┗━┛╺┻┛┗━╸   ┗┻┛┗━┛┗━╸   ┗━┛╹╹┗╸┗┛ ┗━╸   ┗━┛╹ ╹┗━╸┗┛ ╹ ╹╹┗╸   ┗━╸╹ ╹    ╹ ╹┗━╸╹┗╸╹┗╸╹ ╹   ┗━┛╹   ┗━┛┗━╸    ",
		u8"     ┏━┓╻┏━╸┏━┓╺┳┓┏━╸   ┏━╸╻     ┏┓╻┏━┓┏┳┓┏┓ ┏━┓┏━╸   ╺┳┓┏━╸   ╻  ┏━┓┏━┓   ┏━╸┏━┓╺┳╸┏━┓┏━╸╻  ╻  ┏━┓┏━┓┏━┓     ",
		u8"     ┣━┛┃┣╸ ┣┳┛ ┃┃┣╸    ┣╸ ┃     ┃┗┫┃ ┃┃┃┃┣┻┓┣┳┛┣╸     ┃┃┣╸    ┃  ┣━┫┗━┓   ┣╸ ┗━┓ ┃ ┣┳┛┣╸ ┃  ┃  ┣━┫┗━┓ ╺┛     ",
		u8"     ╹  ╹┗━╸╹┗╸╺┻┛┗━╸   ┗━╸┗━╸   ╹ ╹┗━┛╹ ╹┗━┛╹┗╸┗━╸   ╺┻┛┗━╸   ┗━╸╹ ╹┗━┛   ┗━╸┗━┛ ╹ ╹┗╸┗━╸┗━╸┗━╸╹ ╹┗━┛ ╹      ",
		u8"                                                                                                      ",
		u8"                                                                                                      ",
		u8" ┏━ ╺┳╸┏━╸┏━╸╻  ┏━┓┏━┓   ╺┳┓╻┏━┓ ━┓   ┏━╸┏━┓┏┓╻╺┳╸╻┏┓╻╻ ╻┏━┓┏━┓         ┏━ ┏━╸┏━┓┏━╸ ━┓   ┏━┓┏━┓╻  ╺┳╸┏━┓┏━┓  ",
		u8" ┃   ┃ ┣╸ ┃  ┃  ┣━┫┗━┓    ┃┃┃┣┳┛  ┃   ┃  ┃ ┃┃┗┫ ┃ ┃┃┗┫┃ ┃┣━┫┣┳┛   ╺━╸   ┃  ┣╸ ┗━┓┃    ┃   ┗━┓┣━┫┃   ┃ ┣━┫┣┳┛  ",
		u8" ┗━  ╹ ┗━╸┗━╸┗━╸╹ ╹┗━┛   ╺┻┛╹╹┗╸ ━┛   ┗━╸┗━┛╹ ╹ ╹ ╹╹ ╹┗━┛╹ ╹╹┗╸         ┗━ ┗━╸┗━┛┗━╸ ━┛   ┗━┛╹ ╹┗━╸ ╹ ╹ ╹╹┗╸  ",
		}, 8, 7);

	cin.agregarSlide({
		u8"“Debéis amar la paz como  medio  para  nuevas guerras. Y la paz corta más que la",
		u8" larga. A vosotros no os aconsejo el trabajo, sino la lucha. A vosotros no os a-",
		u8" consejo la paz,  sino  la  victoria.¡Sea vuestro trabajo una lucha, sea vuestra",
		u8" paz una victoria! [...] La guerra y el valor han hecho más cosas grandes que el",
		u8" amor al prójimo.  No vuestra compasión, sino vuestra valentía es la que ha sal-",
		u8" vado hasta ahora a quienes se hallaban en peligro.”",
		u8"                                      — Friedich Nietzsche, Así Habló Zaratustra",
		u8"",
		u8" Me senté en una pequeña banca de madera que, hasta el momento, yacía oculta de-",
		u8" bajo de la mesa.  Wilmer,  por  un momento, dudó si acompañarme, pero una larga",
		u8" mirada y un sutil movimiento de Don Evaristo lo convenció.",
		u8" ",
		u8" DON EVARISTO: Kipatsi te ha recibido en su manto. E incluso agonizante, agrade-",
		u8" ció vuestra valentía... o lo que cualquiera  de  nosotros piensa, vuestra falta",
		u8" de cabales... ¿No es así, Wilmer?",
		u8" ",
		u8" WILMER: Pues... —calló un momento, y se le notaba visiblemente nervioso—   Creo",
		u8" que la falta de cabales es lo que caracteriza a los grandes hombres.",
		u8" ",
		u8" DON EVARISTO: En la Quebrada Yonkiri, no ha crecido tan solo un brote en dos a-",
		u8" ños. Y ninguna planta de kamarampi en, quizás, varias décadas.  Pero tu, foras-",
		u8" tero, has hecho algo que nadie del pueblo ha logrado hacer.    Enfrentarse a la",
		u8" muerte, temerariamente, con el grito de VIDA..."
		}, 29, 5);

	cin.agregarSlide({
		u8" DON EVARISTO: Pero aún no lo logro entender...  ¿Qué es lo que te une a la tie-",
		u8" rra? ¿Es la sagrada locura la que te ha hecho tomar tanto riesgo?    ¿O el amor",
		u8" hacia el recuerdo perdido?",
		u8" ",
		u8" ¿Por qué lo hice? ¿Si era probable que no hubiese salido vivo de allí?  La res-",
		u8" puesta más obvia, más insulsa, no tiene valor aquí.  No lo hice por el dossier.",
		u8" Ni por querer caerle bien al anciano, o al pueblo.",
		u8"",
		u8" MATEO: Quizás un poco de los dos.",
		u8" ",
		u8" DON EVARISTO: La tierra... La tierra tiene memoria.   En ella, escribimos nues-",
		u8" tras vidas, nuestras tristezas, nuestras alegrías.   Ella nos permite vivir.  Y",
		u8" cuando morimos, nos acoje en su manto.   Y, finalmente, nos volvemos una con e-",
		u8" lla. Y de este entendimiento, de este respeto, de este amor, es que nacen y cre",
		u8" cen los pueblos.  Si salvas la tierra, pero pierdes el nombre de las estrellas,",
		u8" ¿Qué es lo que realmente has salvado? La vida sigue. Y crece.  Pero su signifi-",
		u8" cado se pierde.  Y esa es la mayor tragedia que precede la muerte de un pueblo.",
		u8" ",
		u8" WILMER: Abuelo Evaristo —Por primera vez, veo a Wilmer dudar—   ¿Nosotros hemos",
		u8" perdido el nombre de las estrellas?"
		}, 29, 7);

	cin.agregarSlide({
		u8" DON EVARISTO: Ya no... Por que algo ha renacido. El árbol sagrado crece en tie-",
		u8" rra muerta. Y nuestros espíritus podrán renacer en un claro muerto.",
		u8" ",
		u8" Don Evaristo se para de su silla, apoyándose de su bastón oscuro.   Y se acerca",
		u8" hacia la mesa, donde reposa la caja tallada con el dossier de pruebas.",
		u8" ",
		u8" DON EVARISTO: Este es el dossier que te prometí  —dice,   sacando de la caja un",
		u8" cuaderno de tapa de cuero gastado— Dos años de pruebas.  Testimonios.  Fotos de",
		u8" los bidones enterrados. Nombres de los que partieron. Fechas. Coordenadas. Todo",
		u8" lo que tu gente llama 'evidencia'.    Pero, en realidad, esto es un saludo a la",
		u8" bandera. Si publicas esa información, ¿Qué pasará? Irán tras la maderera.  Y se",
		u8" irán a un pueblo vecino.  Y nos dejarán con la quebrada muerta y un pueblo tam-",
		u8" bién muerto. Pero en tus manos... hace una diferencia. Por que nos has dado una",
		u8" lección.  Por  que  nos  has recordado que la sangre de los héroes acerca más a",
		u8" Dios que las plegarias de los santos...",
		u8" "
		u8" Antes que Don Evaristo termine con entregarme el dossier, oigo pasos nerviosos.",
		u8" Desesperados. Todos volteamos a ver la puerta.  No puede ser un talador.  Ellos",
		u8" avanzan con un paso lento y burlón.",
		u8" "
		u8" La puerta se abre.  Una silueta aparece bajo el umbral.  Es un hombre.  Delgado,",
		u8" joven. Lo logro reconocer. Es Jeremías."
		}, 29, 7);

	cin.agregarSlide({
		u8" JEREMÍAS: ¡Don Evaristo! ¡Wilmer! ¡Ah... Periodista! ¡Dios... que bien que es-",
		u8" tán aquí. Pero... Necesito decirles algo. Ah... ah...",
		u8" ",
		u8" WILMER: ¿Jeremías? ¿Qué haces aquí?   Sabes bien que no puedes entrar así a la",
		u8" casa del Abuelo Evaristo. Esta no es tu...",
		u8" ",
		u8" JEREMÍAS: ¡Dios, Wilmer, perdóname, pero es urgente! Yo... Yo...",
		u8" ",
		u8" MATEO: [No dudo. El contexto lo demanda]  Tú trabajas para los taladores, ¿no?",
		u8" ¿Qué haces aquí? ¿Has visto algo?",
		u8"",
		u8" JEREMÍAS: ¡Sí, sí, sí! ¡Es... es por lo que hiciste! ¡Por los brotes!   Aún no",
		u8" los han tocado.  Todos...todos están sorprendidos.   Nadie se atreve a quitar-",
		u8" los. Pero... pero si traman algo. Algo fuerte...",
		u8" ",
		u8" WILMER: ¿Algo fuerte? ¿¡Estuviste en la Quebrada Yonkiri!?",
		u8" ",
		u8" MATEO: Creo que sé algo. ¿Un cargamento? ¿Que viene hoy, en la noche, no?",
		u8" ",
		u8" JEREMÍAS: ¡Sí! Un cargamento. De no se qué cosa y qué cuanto.   Pero... lo que",
		u8" si sé es quienes vienen. ¡Son los líderes! ¡Los 'gerentes'! Y han visto lo que",
		u8" hiciste. Y están furiosos...",
		}, 29, 6);

	cin.agregarSlide({
		u8" JEREMÍAS: Saben... saben que te quedaste. Que ignoraste su advertencia. Eso...",
		u8" es inusual. Pero los que vinieron antes también lo hicieron.    Pero... nadie,",
		u8" NADIE, ha ido a la Quebrada. Y peor, nadie a plantado algo allí...",
		u8" ",
		u8" DON EVARISTO: Van a ir tras él— su simpleza fue punzante.",
		u8" ",
		u8" JEREMÍAS: Ay... Sí, sí, sí... Saben que tiene algo más.  Creo que... es el do-",
		u8" ssier, ¿no? Saben el riesgo que corren si se expone. Y van a ir tras él...",
		u8" ",
		u8" La aseveración es simple, directa, agobiante y dolorosa.  Mi cabeza tiene pre-",
		u8" cio. Porque demostré que no era un charlatán.  Pero antes que pudiese interve-",
		u8" nir, o incluso dejar que el miedo se apodere de mí, Don Evaristo habló.",
		u8" ",
		u8" DON EVARISTO: Pues el periodista se tendrá que marchar. Hoy.  Y tendrá que ser",
		u8" escoltado por alguien... Wilmer. Jeremías. Vayan con él. Río abajo. Hasta lle-",
		u8" gar a Satipo. Allí estará seguro. En el río... los taladores lo tragarán.",
		u8" ",
		u8" Los ojos de Wilmer se dilatan,  pero rápidamente asiente a la orden.  Jeremías",
		u8" se ve como que se va a desmayar, mas también asiente.",
		u8" ",
		u8" DON EVARISTO: Es nuestra precoz despedida... Mateo. Te llevarás un pedacito de",
		u8" Kametsa Pampa. Y vivirás por siempre en nuestra memoria...",
		}, 29, 6);

	return cin;
}

Cinematica setupCinNvl3Final() {
	Cinematica cin;

	cin.agregarSlide({
		u8" La persecusión dura toda la noche. El silencio, aquel estado tan natural en las",
		u8" noches ominosas de la selva,   es perturbado por los sonidos de las lanchas, de",
		u8" los disparos, de los gritos, algunos callados, algunos ensordecedores. Río aba-",
		u8" jo. La ruta que recorremos es diferente a la que tomé días atrás. Es más larga.",
		u8" Y parece ir por la Quebrada Yonkiri. Lo infiero, pues los cúmolos de basura, de",
		u8" aquella aterradora espuma colorida que flota en el río,  y el ejército de toco-",
		u8" nes que se ve en la orilla me lo sugiere.",
		u8" ",
		u8" Wilmer es el que maneja. Jeremías va en la retaguardia, asegurándose que el mo-",
		u8" tor funcione. Y yo... yo aprieto con una fuerza titánica el dossier de pruebas.",
		u8" Cada vez que tambalea el bote,  existe el riesgo que una página se pierda en el",
		u8" agua.   Que una foto se moje hasta quedar irreconocible.  O que un recibo quede",
		u8" mezclado con los letales químicos.",
		u8" ",
		u8" Sigue así. Toda la noche. No tenemos paz. Las lanchas de atrás aceleran.   Y si",
		u8" no fuera por su propia ineptitud de convertir el río en una cloaca, en una sopa",
		u8" mortal de troncos, barriles y espuma flotante, lo hubiese hecho.",
		u8" ",
		u8" Oigo chillidos lejanos. Los reconozco. Monos aulladores. Parece que Kipatsi, la",
		u8" gran Madre que los taladores han desafiado,   está componiendo nuestro epitafio",
		u8" en el río y los árboles. Y el requiem de aquellos hombres sin cabales está sien",
		u8" do cantado por los hijos de la naturaleza."
		}, 29, 6);

	cin.agregarSlide({
		u8" Es allí cuando cae la primera gota.  Y la segunda.   Y en un instante, el oscuro",
		u8" cielo se torna gris y la bruma perturba nuestra vista.  Es la atmósfera perfecta",
		u8" para perderse y no regresar jamás...     Y no sabíamos si aquellos que se iban a",
		u8" perder eran nuestros perseguidores o nosotros...",
		u8" ",
		u8" Wilmer, sin embargo,  es un hombre experimentado. La neblina oscurece todo. Pero",
		u8" sus manos conocen el timón.  Su mente conoce el río.  Y aquel conocimiento, hace",
		u8" algunas horas una simple metáfora  de la conexión con la tierra,  es la diferen-",
		u8" cia que nos hace despertar en el ataúd, antes de ser enterrados.",
		u8" ",
		u8" Chocamos. Una. Dos. Cinco, diez veces. Algunas veces son troncos.    Otras veces",
		u8" son barriles. O esa espuma. El bote tambalea. Nosotros tambaleamos.  Y yo me afe",
		u8" rro más al dossier. Recuerdo a Don Evaristo. Y su obvio mensaje.  La tragedia co",
		u8" menzó cuando el hombre se separó de la naturaleza.  Y no supo defenderla.  Ahora",
		u8" nosotros hemos de redimir los errores del pueblo.  Y daremos la vida si es nece-",
		u8" sario.",
		u8" ",
		u8" ¿Y qué más podríamos hacer? Natura nos ofrece un camino, que tiene forma de ata-",
		u8" úd. Y no tenemos otra ruta que recorrer. Lo logremos o no, el impacto ya está he",
		u8" cho. La vida renació en un páramo muerto. Y si nosotros morimos, también renace-",
		u8" remos, en las 'almas moribundas' —como diría Don Evaristo— de todos los hombre y",
		u8" mujeres de Kametsa Pampa.",
		u8" ",
		u8" Somos la voz de un pueblo. Las manos de la naturaleza.   Nuestro propósito es el",
		u8" propósito de algo superior. Kipatsi, diría Don Evaristo.   La Providencia, diría",
		u8" yo."
		}, 29, 5);

	cin.agregarSlide({
		u8" Y la tormenta se disipa. No sé exactamente como. En un momento, estábamos con-",
		u8" duciendo a ciegas.   Y en otro, la bruma se disipaba,  y los primeros rayos de",
		u8" sol penetran el gris éter.",
		u8" ",
		u8" Wilmer no se inmuta. Aunque sus manos tiemblan, su respiración se agita, y sus",
		u8" ojos están cansados, él sigue. Sigue. Y sigue. Tiene un solo objetivo.  Y pase",
		u8" lo que pase, lo cumplirá.",
		u8" ",
		u8" Jeremías, por su parte, no logra contenerse.",
		u8" ",
		u8" JEREMÍAS: ¿Es-Estamos lejos de ellos? No los veo. Y el sol. El sol... Esperen.",
		u8" ¿Ven eso en el horizonte? Es... ¿Es una ciudad?",
		u8" ",
		u8" Una ciudad. Tras lo que pareció ser más de seis u ocho horas, por fin llegamos",
		u8" a la civilización. Y no en una balsa vacía.  Hay tres hombres que han cambiado",
		u8" permanentemente.   Y un cuaderno grueso y maltratado que resonará en todos los",
		u8" rincones del país.",
		u8" ",
		u8" Llegamos al muelle.  Pescadores preparan sus lanchas.  Y no pueden evitar ver-",
		u8" nos. Es lo natural. Nuestra lancha apenas y logra flotar.   Y nuestros rostros",
		u8" no pueden ocultar el peso de los días pasados.",
		u8" ",
		u8" WILMER: Esta es la comunidad vecina de Nantuari.  Para Satipo, te faltaría na-",
		u8" vegar unos días más. Pero... Estamos a salvo. Por ahora..."
		}, 29, 5);

	cin.agregarSlide({
		u8" Bajamos de la lancha. Caminamos.   Nantuari es una comunidad más pequeña, pero",
		u8" también más pacífica. El río es cristalino. Los árboles son abundantes.  Y por",
		u8" ningún lugar se huele el olor a humo negro y químicos industriales.",
		u8" ",
		u8" Wilmer conoce el lugar.  Cuenta, en pocas palabras, que Nantuari es otra comu-",
		u8" nidad asháninka, que años atrás fue arrasada por narcotraficantes.   Pero, que",
		u8" por la valentía de su pueblo, lograron resistir.  Fueron desplazados, pero en-",
		u8" contraron cobijo en su nuevo hogar. Otra historia de resistencia. De un pueblo",
		u8" que renació.  Una historia que vive en la mente y en las almas de sus habitan-",
		u8" tes. Y que ningún papel o registro audiovisual capturó.",
		u8"",
		u8" En esa paz, solamente queda pensar en el futuro. Y en la 'nostalgia de lo per-",
		u8" dido'.  En las palabras de Don Evaristo,  que, pienso,  son lo más valioso que",
		u8" encontré en este viaje. Es verdad: la tierra y los pueblos pueden salvarse, pe",
		u8" ro... ¿De qué sirve salvarlos, si se pierde el nombre de las estrellas?",
		u8" ",
		u8" Pero no puedo quedarme en Nantuari.  Esta paz es solo tempora.  Acabará cuando",
		u8" llegue a Lima. Cuando escriba el artículo.  Cuando lo publique. Y allí... aca-",
		u8" bará solamente la primera etapa. Porque este aprendizaje...     durará toda mi",
		u8" vida. Me despido de Wilmer. De Jeremías. Y desde lejos, de Don Evaristo.",
		}, 29, 6);

	return cin;
}